spring:
  application:
    name: myCommerce

  output:
    ansi:
      enabled:always

  logging:
    pattern:
      console: "%clr(%d{HH:mm:ss}){yellow} %clr(%-5level){green} %clr(%logger{36}){cyan} - %msg%n"

  datasource:
    url: jdbc:mysql://localhost:3306/mycommerce
    username: root
    password: chirag
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always