spring:
  application:
    name: myCommerce


  datasource:
    url: jdbc:mysql://localhost:3306/mycommerce
    username: root
    password: chirag
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
